### ISSUE TITLE
TTL is not working ....

### ISSUE THREAD

**Issue by balaphp** [hueniverse/iron#41]
var Iron = require('iron');

			var obj = {
			    a: 1,
			    b: 2,
			    c: [3, 4, 5],
			    d: {
			        e: 'f'
			    }
			};

			var password = 'some_not_random_password';

			var defaults = JSON.parse(JSON.stringify(Iron.defaults));

			defaults.ttl = 2;
			defaults.timestampSkewSec = 1;

			Iron.seal(obj, password, defaults, function (err, sealed) {

				console.log("IRON..");
			    console.log(sealed);
			    setTimeout(function(){
			    	Iron.unseal(sealed, password, Iron.defaults, function (err, unsealed) {
						console.log("IRON..");
						console.log(err);
					    console.log(unsealed);
					});
			    },2000);

			});

Sorry i may be wrong. In this sample it should show TTL error in unseal operation with Iron.defaults. 
its showing TTL error if i used  defaults in unseal...

**Comment by cjihrig** [comment]
`Iron.unseal(sealed, password, Iron.defaults,...`

You aren't unsealing with your modified parameters, so `timestampSkewSec` is still 60 seconds.

**Comment by balaphp** [comment]
Yes... the thing is Iron seal operation not including the TTL or timestampSkewSec value in the encryption model. So other side person can able to do the unseal operation successfully with his own parameters.

**Comment by hueniverse** [comment]
It's not designed to prevent you from being able to unseal expired tokens. It's designed to protect you from expired tokens.
