### ISSUE TITLE
Markdown parser causes some jank in README

### ISSUE THREAD

**Issue by newswim** [hueniverse/iron#54]
Since Github has transitioned to supporting only [their own GFM dialect](https://githubengineering.com/a-formal-spec-for-github-markdown/), it's broken a lot of md files. I noticed some broken links in the repo, happy to do a PR :)

<img width="1083" alt="screen shot 2017-06-16 at 5 45 05 pm" src="https://user-images.githubusercontent.com/6667096/27247129-c2658ae2-52bb-11e7-89f3-22407c5b6762.png">

**Comment by hueniverse** [comment]
I'll take a PR. Thanks.

**Comment by newswim** [comment]
#56 should fix it!

**Comment by hueniverse** [comment]
Thanks.
