### ISSUE TITLE
Iron.seal is not working 

### ISSUE THREAD

**Issue by alqamabinsadiq** [hueniverse/iron#66]
I was using this method and the callback was returning me the sealed value but after upgrading the version it stopped working.

``` 
Iron.seal(data, sealPass, Iron.defaults, (err, sealed) => {
    if (err) {
      console.log(err);
    }
    console.log(sealed);
  }); 
```

**Comment by hueniverse** [comment]
Because the module was moved to async/await but the docs were not updated yet.

**Comment by alqamabinsadiq** [comment]
Thanks!
